### ISSUE TITLE
Latest relaton gets rid of init_bib_caches

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton#102]
standoc calls that. Please advise what I should be doing instead.

**Comment by andrew2net** [comment]
@opoudjis what is the full command does standoc call? `Relaton::Db.init_bib_caches` is still presents:
```ruby
> require 'relaton'
=> true

> Relaton::VERSION
=> "1.12.3"

> db = Relaton::Db.init_bib_caches
=> #<Relaton::Db:0x00007f83cd0a8d88
...
```
