### ISSUE TITLE
(URGENT) Address structural discrepancies across Relaton data sources

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton#108]
From @strogonoff https://github.com/ietf-tools/bibxml-service/issues/283#issuecomment-1232702426

There are structural discrepancies reported by @strogonoff across the different Relaton data sources.

Could we split these tasks into their relevant repos? Thanks.

> * [IANA](https://raw.githubusercontent.com/ietf-tools/relaton-data-iana/main/data/bgp-extended-communities_arp-nd-extended-community-flags.yaml):
> 
> ```
> contributor -> 0 -> organization -> abbreviation
>   str type expected (type=type_error.str)
> ```
> 
>  * [IEEE](https://raw.githubusercontent.com/ietf-tools/relaton-data-ieee/main/data/ANSI_IEEE_991-1986.yaml):
> 
> ```
> contributor -> 0 -> organization -> abbreviation
>   str type expected (type=type_error.str)
> keyword
>   str type expected (type=type_error.str)
> keyword -> 0
>   str type expected (type=type_error.str)
> copyright -> 0 -> owner -> 0 -> name -> 0
>   str type expected (type=type_error.str)
> copyright -> 0 -> owner -> 0 -> name
>   str type expected (type=type_error.str)
> copyright -> 0 -> owner -> 0 -> abbreviation
>   str type expected (type=type_error.str)
> copyright -> from
>   field required (type=value_error.missing)
> copyright -> owner
>   value is not a valid list (type=type_error.list)
> ```
> 
> * [ID](https://raw.githubusercontent.com/ietf-tools/relaton-data-ids/main/data/draft-ayers-low-power-interop-02.yaml):
> 
> ```
> contributor -> 0 -> person -> name -> given -> forename -> 0
>   Forename.__init__() missing 1 required positional argument: 'content' (type=type_error)
> contributor -> 0 -> person -> name -> given -> forename -> content
>   str type expected (type=type_error.str)
> ```
> 
>  * [MISC](https://raw.githubusercontent.com/ietf-tools/relaton-data-misc/main/data/reference.W3C.soap11.yaml):
> 
> ```
> contributor -> 0 -> person -> name -> given -> forename -> 0
>   Forename.__init__() missing 1 required positional argument: 'content' (type=type_error)
> contributor -> 0 -> person -> name -> given -> forename -> content
>   str type expected (type=type_error.str)
> ```
> 
>  * [NIST](https://raw.githubusercontent.com/ietf-tools/relaton-data-nist/main/data/NBS_BH_1.yaml):
> 
> ```
> contributor -> 8 -> organization -> abbreviation
>   str type expected (type=type_error.str)
> ```
> 
> * [RFCS](https://raw.githubusercontent.com/ietf-tools/relaton-data-rfcs/main/data/RFC0001.yaml):
> 
> ```
> contributor -> 0 -> person -> name -> given -> forename -> 0
>   Forename.__init__() missing 1 required positional argument: 'content' (type=type_error)
> contributor -> 0 -> person -> name -> given -> forename -> content
>   str type expected (type=type_error.str)
> ```

- `organization -> abbreviation` cases should be covered by normalization in #282
- `person -> name -> given -> ...` cases should be covered by normalization in #282
- `keyword -> ...` cases should be covered by normalization in #278
- `copyright -> 0 -> owner -> ...` cases still need attention (validation errors here: https://bib.ietf.org/indexed-sources/relaton-data-ieee/ANSI_IEEE_991-1986/)

**Comment by ronaldtse** [comment]
Split into individual tasks now:

* [ ] https://github.com/relaton/relaton-iana/issues/15
* [ ] https://github.com/relaton/relaton-nist/issues/83
* [ ] https://github.com/relaton/relaton-ieee/issues/32
* [ ] https://github.com/relaton/relaton-ietf/issues/107

**Comment by strogonoff** [comment]
@ronaldtse many of these had been fixed in relaton-py, but not made their way to BibXML service production yet. Should be done as part of the PR.

**Comment by andrew2net** [comment]
@ronaldtse we had structure simplification in the YAML output, so instances of LocalizedString or FormattedRef could be rendered as strings in case only content is present. This caused inconsistency in YAML output. Now all instances of the classes are rendered as objects, so the bibxml-service should adopt the format.
