### ISSUE TITLE
If Relaton gem sees any load error or yaml error in the cached index (or any cached documents), it should consider the cache as corrupt and wipe it

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton#112]
From https://github.com/relaton/relaton-bipm/issues/45

If Relaton gem sees any load error or yaml error in the cached index (or any cached documents), it should consider the cache as corrupt and wipe it.

Right now, on load error or YAML parsing errors, the Relaton gems will just crash. Crashing is never acceptable behavior. We should tell the users why it's crashing, and if it's crashing, tell the user what we will do to mitigate this.

e.g. if redownload successful
```
[relaton] YAML parsing error when reading file ~/.relaton/bipm/index.yaml
[relaton] Considering ~/.relaton/bipm/index.yaml file corrupt, re-downloading from https://github.com/relaton/relaton-data-bipm/xxx
[relaton] Loaded index from ~/.relaton/bipm/index.yaml
```

e.g. if remote index is also corrupt
```
[relaton] YAML parsing error when reading file ~/.relaton/bipm/index.yaml
[relaton] Considering ~/.relaton/bipm/index.yaml file corrupt, re-downloading from https://github.com/relaton/relaton-data-bipm/xxx
[relaton] YAML parsing error when reading newly downloaded file at ~/.relaton/bipm/index.yaml , the remote index seems to be broken. Please report this issue at https://github.com/relaton/relaton-cli.
```

**Comment by andrew2net** [comment]
@ronaldtse the relaton doesn't operate with any indexes. The flavor gems that use indexes to search documents do it. We can hadle YAML parsing error in the relaton-index, but format of an index depends on a flavor gem. So this issue should be fixed in each flavor gem.

**Comment by ronaldtse** [comment]
OK then we have to fix it in every flavor gem. I still think that the Relaton db cache (e.g. in Metanorma we often use it in local mode, meaning that a new cache is used in the local directory) should contain both the cached documents and the index, because the consistency of both the index and the cached documents are related.

**Comment by andrew2net** [comment]
Since we have integrated a `relaton-index` gem in all `relaton-data-*` repos, we can fix this issue in the gem.

**Comment by andrew2net** [comment]
These gems need to implement index structure checking:
- [ ] relaton-bipm
- [ ] relaton-iho
- [ ] relaton-iec
- [ ] relaton-ecma
- [ ] relaton-w3c
- [ ] relaton-ietf
- [ ] relaton-calconnect
- [ ] relaton-iana
- [ ] relaton-oasis
- [ ] relaton-itu
- [ ] relaton-3gpp
- [ ] relaton-ogc
- [ ] relaton-cie
- [ ] relaton-nist
- [ ] relaton-ieee
