### ISSUE TITLE
not showing full names of ISO and ISO/IEC standards

### ISSUE THREAD

**Issue by jonsneyers** [relaton/relaton#118]
Perhaps something changed on the ISO web pages that is causing parsing to partially fail, but it looks like references are not complete anymore, e.g. for these references (in metanorma syntax):

```
* [[[icc, ISO 15076-1]]], _Image technology colour management — Architecture, profile format and data structure — Part 1: Based on ICC.1:2010_

* [[[float, ISO/IEC 60559]]], _Information technology — Microprocessor Systems — Floating-Point arithmetic_

* [[[json, ISO/IEC 21778]]], _Information technology — The JSON data interchange syntax_
```

I end up getting the following output:

ISO 15076-1, Image technology colour management
ISO/IEC 60559, Information technology
ISO/IEC 21778, Information technology

**Comment by ronaldtse** [comment]
@jonsneyers yes ISO recently changed their structure and you will need to upgrade to the latest relaton-iso version. Do you know how to do that?

**Comment by jonsneyers** [comment]
Ah, I was assuming it would automatically upgrade but looks like it didn't. OK sorry :)

**Comment by ronaldtse** [comment]
Great to know that it's resolved. Thanks!

**Comment by jonsneyers** [comment]
Sorry, I thought it would be resolved by doing `sudo gem update relaton-iso` (which did do something so I indeed didn't have the latest version), but it looks like I still have the issue. Is there anything else that I need to do?

**Comment by ronaldtse** [comment]
I'm on relaton-iso 1.16.3 and the snippet provided the following output which I think looks normal:

<img width="833" alt="Screenshot 2023-10-27 at 10 30 03 PM" src="https://github.com/relaton/relaton/assets/11865/91cd730e-4f1e-4070-b838-92049c660da4">

Can you try doing:
```sh
$ sudo gem update metanorma-cli
```

? 

I'm hoping it will update a lot more.

**Comment by jonsneyers** [comment]
Right, that solves it. Looks like I was using some `snap` version of metanorma, which was somehow using an old relaton even when the system relaton was updated. I removed the `snap` thing, now I'm just using the metanorma-cli gem and that seems to work fine.
Thanks!
