### ISSUE TITLE
Update all relaton-data-* repository to branch `main` instead of `master`

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton#129]
We should change the branches to `main` now.

@andrew2net what steps do we have to take?

**Comment by andrew2net** [comment]
@ronaldtse to chna

**Comment by andrew2net** [comment]
@ronaldtse I don't have permission to change default branch on GitHub https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch
