### ISSUE TITLE
Import bibtex into relaton

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton#32]
This will involve a mapping of bibtex into relaton, which I will provide. @ronaldtse will need to provide more information about how this will be used; it may be attached to relaton-cli, but I suspect it will be invoked from within metanorma.

**Comment by ronaldtse** [comment]
@andrew2net , the point is to connect https://github.com/riboseinc/asciidoctor-bibliography with the Relaton gem so that Relaton can use the BibTeX file as a data source.

**Comment by opoudjis** [comment]
@andrew2net The mapping of bibtex to relaton in #37 is done.

**Comment by ronaldtse** [comment]
Export to BibTeX is also necessary, perhaps in a new issue after this.

**Comment by andrew2net** [comment]
can we close the issue?

**Comment by andrew2net** [comment]
> @andrew2net The mapping of bibtex to relaton in #37 is done.

can we close the issue?

**Comment by ronaldtse** [comment]
@andrew2net this task is to allow importing BibTeX files into Relaton. Can you implement it by integrating https://github.com/riboseinc/asciidoctor-bibliography gem with Relaton/Metanorma? Thanks.

**Comment by opoudjis** [comment]
@ronaldtse Isn't this task overridden by https://github.com/metanorma/relaton/issues/48?

**Comment by andrew2net** [comment]
the #48 overrides this issue and more informative
