### ISSUE TITLE
BibTeX parsing, integration with `asciidoctor-bibliography` gem

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton#48]
In Relaton we should be able to import BibTeX, and we should also be able to export BibTeX.

For input, we will need to implement these methods:

* `relaton_object.to_bibtex`
* `Relaton.from_bibtex(bibtex)` (defer to `asciidoctor-bibliography`)

For output/rendering, we should support CSL output as performed in `asciidoctor-bibliography`. i.e. we could possibly just integrate with it.

_Originally posted by @ronaldtse in https://github.com/metanorma/relaton/issues/37#issuecomment-494828903_

ping @opoudjis @paolobrasolin

**Comment by ronaldtse** [comment]
This is time-sensitive work. Thanks!

**Comment by ronaldtse** [comment]
A short intro to this task:

Users want to use BibTeX files in Metanorma. Metanorma uses Relaton, which is a new citation data model for ISO 690. So we need to integrate the bibtex parsing part from asciidoctor-bibliography into Relaton (probably a new gem, since Relaton will also support other formats like EndNote in the future).

**Comment by opoudjis** [comment]
So, I need the following from you, @paolobrasolin.

I need a function that is passed a BibTeX file, containing a collection of BibTeX items, each with a database key. That function needs to return a hash of database keys to RelatonBib::BibliographicItem records, one record for each BibTeX record. You will find the class and its initialisers in https://github.com/metanorma/relaton-bib. The gem is being maintained by @andrew2net.

So:

````
@article{mrx05, 
auTHor = "Mr. X", 
Title = {Something Great}, 
publisher = "nobody", 
YEAR = 2005, 
} 
````

Will map to:

````
{ "mrx05" => RelatonBib::BibliographicItem.new(
id: "mrx05",
 titles: [
          { type: "main", content: "Something Great" }
],
contributor: [
    { 
entity: RelatonBib::Person.new(
              name: RelatonBib::FullName.new(
                completename: "Mr. X",
              ),
roles: ["author"]
    },
{
entity: {name: "nobody"},
roles: ["publisher"]
}
],
dates: [
          { type: "published", on: "2005" }
        ]
)
````

I do not need any CSL or any serialisation: relaton already has its own serialisation to XML. I need a class that I can integrate into the relaton-bib gem, as an importer and exporter; I don't see the need to use asciidoctor-bibliography (although the class you give me can call it).

**Comment by opoudjis** [comment]
The mapping of BibTeX to relaton is https://github.com/metanorma/relaton/issues/37. The mapping there is to Relaton XML, but this ticket requests that you map to the Relaton object constructor. Hopefully you can infer the latter from the former. Please ask questions as you go.

**Comment by opoudjis** [comment]
From https://github.com/metanorma/metanorma-ogc/issues/41

>>When bibliographic entries are parsed, before passing their keys on to Relaton for fetching, check to see if they already occur in the parsed BibTex file

>I think we should just treat BibTeX files as a type of Relaton database -- a relaton-db-bibtex gem? We will have other types of Relaton databases, such as Endnote and RIS. So it will be useful to have a common interface for these to hook into.

@paolobrasolin, you discuss that with @ronaldtse; I'm not going to be involved in any Relaton refactoring. @andrew2net, FYI for now.

**Comment by paolobrasolin** [comment]
@opoudjis I agree with you, integrating `asciidoctor-bibliography` seems like overkill.

`asciidoctor-bibliography` itself is using `bibtex-ruby` to read BibTeX files.
Its [Entry](https://www.rubydoc.info/gems/bibtex-ruby/BibTeX/Entry) should be relatively easy to map onto `relaton`'s objects. Furthermore, it can export back to BibTeX so it should fit the bill perfectly.

Does this sound good to you?

**Comment by ronaldtse** [comment]
@paolobrasolin the idea with integration is not necessarily integration with the current form of "asciidoctor-bibliogrpahy", but in two ways:

1. We need a way to accept BibTeX files in the bibliographic management system within Metanorma (i.e. a database of bibliographic items that can be fetched from Metanorma).

2. We need a way to render bibliographic items chosen from that database, in a CSL-like way. So far we have encountered two kinds of CSL-like (but not available to CSL) rendering.

  * NIST standards uses a NIST CSL (a derivative from PNAS) for cited non-standards. But NIST CSL does not support NIST standards (or any standards). NIST standards use document identifiers and document stage codes that are not supported (it is possible to help NIST update their CSL, if that's the way to go).

  * OGC standards uses a LNCS CSL for cited non-standards. But LNCS CSL does not support citing standards, with their document identifiers (it is possible to help OGC create a CSL)

On the other hand, ISO documents use the ISO 690 style. Its data model is a strict superset of CSL. I may be wrong, but it may be a long stretch to have CSL support the ISO 690 data model.

**Comment by ronaldtse** [comment]
@paolobrasolin @opoudjis @andrew2net  would you have time to do this?

**Comment by andrew2net** [comment]
Is anybody doing this task?

**Comment by ronaldtse** [comment]
I don't think so, @andrew2net can you do it?

**Comment by andrew2net** [comment]
@ronaldtse sure, I will

**Comment by andrew2net** [comment]
@ronaldtse what type of document should we create in `to_bibtex` function?
BibTex allows: article, book, booklet, inbook, incollection, inproceedings, manual, mastersthesis, misc, phdthesis, proceedings, techreport, unpublished. 
According to https://github.com/relaton/relaton/issues/37#issuecomment-494780967 type of document type => `bibitem/@type`. Usually, the type is `standard`. What of BibTex allowed types should we use to store standards?

**Comment by ronaldtse** [comment]
@andrew2net good point. For standards, I previously used “misc”. The standards that are “technical reports” can be tagged as “techreport”.
