### ISSUE TITLE
Add source: W3C

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton#50]
As title

**Comment by andrew2net** [comment]
@ronaldtse do you mean we need a new `relaton-w3c` gem to parse www.w3.org?

**Comment by ronaldtse** [comment]
Yes, thanks @andrew2net

**Comment by andrew2net** [comment]
@ronaldtse suppose we need to search the standards on this page https://www.w3.org/TR/
Do you have suggesting how the references should look like?

**Comment by ronaldtse** [comment]
@andrew2net I think the references look like:

Only with title: "W3C JSON-LD 1.1"
With doctype: "W3C Recommendation JSON-LD 1.1"

<img width="341" alt="Screen Shot 2020-03-07 at 8 35 13 AM" src="https://user-images.githubusercontent.com/11865/76132572-91ea7a00-604e-11ea-94f0-52432fb860b0.png">

With date: "W3C Recommendation JSON-LD 1.1 2019-12-12"
https://www.w3.org/standards/history/json-ld11

<img width="728" alt="Screen Shot 2020-03-07 at 8 34 42 AM" src="https://user-images.githubusercontent.com/11865/76132557-8008d700-604e-11ea-82b0-a534bd7c15d8.png">

With document ID: "W3C json-ld11" or "https://www.w3.org/TR/json-ld11/"

<img width="471" alt="Screen Shot 2020-03-07 at 8 35 47 AM" src="https://user-images.githubusercontent.com/11865/76132596-a62e7700-604e-11ea-9c86-2cc98db69068.png">

**Comment by andrew2net** [comment]
> With doctype: "W3C Recommendation JSON-LD 1.1"

@ronaldtse could we use a short version of doctypes: "W3C REC Trace Context - Level 1"?
This makes it easier to distinguish a doctype form a title.

**Comment by ronaldtse** [comment]
I think we should allow both:
* `W3C REC Trace Context - Level 1`
* `W3C Recommendation Trace Context - Level 1`
?

**Comment by andrew2net** [comment]
@ronaldtse seems we can allow both now because there is no type's name in any title's beginning, but can we be sure it won't be in the future?

**Comment by ronaldtse** [comment]
@andrew2net "Recommendation" is their name for "Standard" so it is unlikely they will use that as a topic name. 

Let's close this issue since relaton-w3c now exists. Thanks!

**Comment by andrew2net** [comment]
> With date: "W3C Recommendation JSON-LD 1.1 2019-12-12"
> https://www.w3.org/standards/history/json-ld11

@ronaldtse with a date it should give us only another link to the document and publication date, all other information should remain as in the last version, shouldn't it?
