### ISSUE TITLE
Add source: OMG

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton#51]
As title.

**Comment by andrew2net** [comment]
@ronaldtse do we need to parse www.omg.org?

**Comment by ronaldtse** [comment]
@andrew2net you're right. Thanks!

**Comment by andrew2net** [comment]
@ronaldtse could we get access to full documents search?

**Comment by andrew2net** [comment]
@ronaldtse I've tried the search page https://www.omg.org/cgi-bin/apps/doclist.pl
It searches by subgroups but I didn't manage to find anything by keywords. I suppose we can search by subgroups if it's possible to extract a subgroup from reference. What would the references for OGM documents look like?

**Comment by ronaldtse** [comment]
It seems that the search functionality is limited:

Here are some existing documents:
<img width="1202" alt="Screen Shot 2020-02-06 at 9 40 54 PM" src="https://user-images.githubusercontent.com/11865/73942063-5c585100-4929-11ea-9678-838f8af4eee9.png">

Can search by "acronym" (e.g. "ASCQM"):
<img width="674" alt="Screen Shot 2020-02-06 at 9 41 26 PM" src="https://user-images.githubusercontent.com/11865/73942100-6ed28a80-4929-11ea-9db4-90d1dbcf8268.png">

Can search by name (e.g. OMG System Modeling Language):

<img width="628" alt="Screen Shot 2020-02-06 at 9 41 53 PM" src="https://user-images.githubusercontent.com/11865/73942130-7e51d380-4929-11ea-9a25-5ef4b55b01a9.png">

Notice in the results there is a document identifier, like "formal/19-11-02". But this cannot be found:

Search with "19-11-02" or "formal/19-11-02":
<img width="288" alt="Screen Shot 2020-02-06 at 9 42 33 PM" src="https://user-images.githubusercontent.com/11865/73942178-96295780-4929-11ea-88a6-4266d2bd8e1c.png">

So I found a reasonable way of searching ALL the documents:
* select ALL the subgroups or ALL the years.

<img width="791" alt="Screen Shot 2020-02-06 at 9 45 28 PM" src="https://user-images.githubusercontent.com/11865/73942427-ff10cf80-4929-11ea-8882-b3d5f9604389.png">

...

<img width="632" alt="Screen Shot 2020-02-06 at 9 45 38 PM" src="https://user-images.githubusercontent.com/11865/73942442-0506b080-492a-11ea-9afb-e50ce02fc728.png">

Might be an overkill...

**Comment by ronaldtse** [comment]
I wonder if the correct way of citing is like this: "OMG {acronym} {version}", e.g. "OMG ADA 1.3" will give you the URI https://www.omg.org/spec/ADA/1.3 , which contains metadata of this document to scrape.

"OMG ADA" will directly point to the "current version", which can be found on https://www.omg.org/spec/ .

We can just consider this page https://www.omg.org/spec/ to be the full list of specs (and acronyms), and then append the version number to it.

<img width="1193" alt="Screen Shot 2020-02-06 at 9 49 09 PM" src="https://user-images.githubusercontent.com/11865/73942721-82cabc00-492a-11ea-834e-952347c023a4.png">

What do you think?

**Comment by andrew2net** [comment]
I think if we have references like `OMG {acronym} {version}` the easiest way is making a link from a reference. e.g. `https://www.omg.org/spec/{acronym}/{version}`

**Comment by ronaldtse** [comment]
I agree, let's go with it

**Comment by andrew2net** [comment]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/5623890/74103685-cfa7d000-4b80-11ea-925d-71891c5b9609.png">
@ronaldtse should we store `Categories` and `IPR Mode` in relaton model? If yes which relaton model's attrubetes shoud we map them?

**Comment by ronaldtse** [comment]
@andrew2net absolutely we should. Ping @opoudjis:

* Should we place "categories" in "keywords"?
* IPR mode - does this go under "license"?

**Comment by opoudjis** [comment]
IPR to license: I don't see any better place for them. Categories can go to classification instead of keywords if they are key/value pairs, but keywords are simpler to deal with: if they fit, fine.
