### ISSUE TITLE
Relaton cache should work according to document identifiers

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton#53]
The Relaton cache should use its knowledge about document identifiers to properly name (and de-duplicate) cached items.

The quoted messages are from @andrew2net. My answers are inline.

> Concerning using a document identifier. We can't use a document identifier as a filename. The problem is we don't have a document identifier when fetching a document. We have a reference only. Before we retrieve the document from the internet we should check if there is a file with a name matched to the reference.
>
> There are other cases like `all parts`, attempts ISO/IEC and stages, when one document could be fetched by different references. If we save these documents using their document identifiers, how do we find the files by references?

When Relaton is asked to retrieve a bibdata, it fetches it according to a known document identifier structure. There are two types of requests:

A. The bibdata requested is for a particular document or a "dated reference" (e.g. "ISO 9001:2015"). There can only be ONE exact match and the document must exist.

B. The bibdata requested is for not a specific document:
B1. It is for an "undated reference" (e.g. "ISO 9001" instead of "ISO 9001:2015"). Here "ISO 9001" means the latest version of "ISO 9001:2015")
B2. It is for a multi-part reference. (e.g. "ISO 639 (all parts)" means all parts of ISO 639 => ISO 639-2, ISO 639-3....)

The outcome of A can be:

1. Document found
2. Document not found
3. Document exact match not found, but similar found (e.g. the document is a multipart document, the document has been withdrawn...)

We need to decide what happens with B1 and B2:
* B1 and A must be considered separately because B1 is a movable reference (i.e. it is a LINK to the latest reference)
* B2 should link up all parts (i.e. it is a COLLECTION of parts)

> One document could be fetched by many different references. For example "ISO 123 2014" returns a document and we save it to `iso_123_2014`. If we search by "ISO 124" reference we will get the same document if it is the lastest with the number. But we don't know it before we fetch the document.

Let's not mix up the two things. There is the "search", and there is the "caching".

The current "cache" does two things that can be independent (there can be two "caches"):
* It helps us return search results offline (search cache)
* It is a database for references for rendering (data cache)

The way search works is:
1. User enters a search string in the document identifier structure
2. Relaton parses the search string and obtains the document's document identifier
3. Relaton uses the document's document identifier to search

The internal representation of the Relaton cache today is mainly implemented in the "data cache" way.

For the "data cache", the handling of REAL document entries (A) should be different from (B1) and (B2). The document bibdata "cache key" should be exactly based on the document identifier in a deterministic (and reversible) way. This `docid <=> cachekey` function can be different for every flavor.

For example for ISO "document identifiers":

* "ISO 9001:2015" => "iso_9001_2015"
* "ISO 9001:2000"=> "iso_9001_2015"

For B1 and B2, we need a different method. We can call these "reference identifiers" because they are not "document identifiers" e.g.

* "ISO 9001" => "iso_9001"
* "ISO 639"=> "iso_639_all"

(and here, we use the `cachekey` for the filename as `{cachekey}.xml`)

This way you can reversibly find the `docid` from the `cachekey` and therefore the file.

For the "search cache", you can store:

* `query => document identifier" and
* `query => reference identifier => document identifier(s)"

As an example, if we separate the "document identifier" with the "reference identifier", it is more clear that "ISO 9001" leads to "ISO 9001:2015", and the last fetch dates of both can be different.

_Originally posted by @andrew2net in https://github.com/metanorma/relaton-iso/issues/58#issuecomment-518177956_

**Comment by ronaldtse** [comment]
Related to https://github.com/metanorma/relaton/issues/52

**Comment by ronaldtse** [comment]
Original problem:

In geolexica.org , both of these files are created in the cache:

* `iso_12620_1999.xml`
* `iso_12620_1999_.xml`

Both files have the same content. Obviously when Relaton creates the cache file, it must be using the normalized document identifier, not what was directly given. e.g. given "ISO 12620:1999 - blah", the normalized filename should still be `iso_12620_1999.xml`.

There are 7 of these in geolexica.org:

* `iso_12620_1999.xml` and `iso_12620_1999_.xml`
* `iso_31_2_1992.xml` and `iso_31_2_1992_.xml`
* `iso_8601_2000.xml` and `iso_8601_2000_.xml`
* `iso_iec_11179_3_2003.xml` and `iso_iec_11179_3_2003_.xml`
* `iso_22028_1.xml` and `iso_22028_1_.xml`
* `iso_iec_19501_2005.xml` and `iso_iec_19501_2005_.xml`
* `iso_iec_tr_14252.xml` and `iso_iec_tr_14252_.xml`

**Comment by andrew2net** [comment]
@ronaldtse we can make `request => filename` index YAML file like:
```yaml
"ISO 9001": iso_9001_2015
"ISO 9001:2015": iso_9001_2015
...
```
There are 2 phases of documents fetching. In the first, we get a search result. In the second we get a document's data. In most flavors, we can obtain `docid` in the first phase. if a file matched to the `docid` already exists, we add a new pair of `request => filename` to the index.
So in each request, it should checks if the request exists in the index. In case the request not found in the index it should perform the first fetching phase to obtain `docid` and check matched file exists. If the file exists then it adds a new pair of `request => filename` to the index. If no then it performs the second fetch phase and creates a new file.

**Comment by ronaldtse** [comment]
> we can make request => filename index YAML file like

Right.

Regarding this:
```
"ISO 9001": iso_9001_2015
"ISO 9001:2015": iso_9001_2015
```

I believe `"ISO 9001": iso_9001_2015` should be handled differently than `"ISO 9001:2015": iso_9001_2015`. `"ISO 9001"` is an undated reference, it should point to a reference that is a "redirection" to `iso_9001_2015`. i.e. a special Relaton XML file that implements "delegation"/"redirection".

**Comment by andrew2net** [comment]
@ronaldtse now file names are generated form a `docidentifier`. I didn't implement 2 phases document fetchig because it needs to update all `relaton-*` gems. I don't think we need to do such a big work because in the geolexica.com I got only one document with a reference different form the `docidentifier`.

**Comment by ronaldtse** [comment]
@andrew2net I'm a bit confused of not doing 2 phase fetching. Don't we already do it now?

**Comment by ronaldtse** [comment]
>  I didn't implement 2 phases document fetchig because it needs to update all relaton-* gems. I don't think we need to do such a big work because in the geolexica.com I got only one document with a reference different form the docidentifier.

This depends on the flavor. For example, OGC and NIST documents depend on a single file, so they don't need a second fetch.

For ISO, we need a second fetch because that's how we obtain the full data.

Right?

**Comment by andrew2net** [comment]
@

> @andrew2net I'm a bit confused of not doing 2 phase fetching. Don't we already do it now?

@ronaldtse yes we do it now but `relaton` gets documents from flavors gems invoking one `get` function. So the flavor gems perform 2 phases at once. To be able invoking phases from `relaton` gem it needs to implement separated functions for the first and the second phases in all flavor gems.

**Comment by andrew2net** [comment]
> This depends on the flavor. For example, OGC and NIST documents depend on a single file, so they don't need a second fetch.
> 
> For ISO, we need a second fetch because that's how we obtain the full data.

@ronaldtse NIST also needs to get search result first and obtain rest data in a second request (except SP/FISP documents, we get them from a JSON file). Don't know about OGC, it isn't implemented yet. `ietf` gem gets documents by their numbers, it doesn't need to get search results.

**Comment by ronaldtse** [comment]
> To be able invoking phases from relaton gem it needs to implement separated functions for the first and the second phases in all flavor gems.

@andrew2net why do we need to invoke phases from relaton  gem?

> @ronaldtse NIST also needs to get search result first and obtain rest data in a second request (except SP/FISP documents, we get them from a JSON file). Don't know about OGC, it isn't implemented yet. ietf gem gets documents by their numbers, it doesn't need to get search results.

Right.

**Comment by andrew2net** [comment]
> @andrew2net why do we need to invoke phases from relaton gem?

@ronaldtse in case we have a lot of references not match to `docidentifier` it could speed up document fetching because we can get `docidentifier` in a first phase, and if a file already exists then a second phase isn't needed. But, as I said before, compiling termbase of geolexica.com gives only one reference not matching to `docidentifier`. So I think we dont need to inplement 2 phases in `relaton` now.

**Comment by ronaldtse** [comment]
@andrew2net which is the one not matching?

**Comment by andrew2net** [comment]
@ronaldtse by reference `ISO 21000-5` we get a document with id `ISO/IEC 21000-5`

**Comment by ronaldtse** [comment]
@andrew2net I see. I really think in this case we need to differentiate `ISO 21000-5` and `ISO/IEC 21000-5` in the filename.

* The `ISO 21000-5` must be recorded as an "alias" to  `ISO/IEC 21000-5`
* The cached data should be stored in `ISO/IEC 21000-5`.

**Comment by andrew2net** [comment]
@ronaldtse it works as said. The file `db/iso/iso_21000_5.xml` contains
```
redirection ISO(ISO/IEC 21000-5)
```
which points to `db/iso/iso_iec_21000_5.xml`

**Comment by ronaldtse** [comment]
Excellent! Very pleased with the results. As an enhancement I’d request the separation of the search cache (not founds and redirects) and the data cache (only relaton xml). Perhaps in a new issue.
