### ISSUE TITLE
Relaton should replace `version` number after refreshing cache

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton#54]
> But before that it sounds we have to fix the local caching mechanism first. As it always shows "Local cache version is obsolete." right now and fetches in Relaton every time. Will post a new issue...

_Originally posted by @PeterTKY in https://github.com/metanorma/metanorma-standoc/issues/99#issuecomment-521092043_

I have also encountered this problem. 

The problem is on updating the Relaton version:

* Relaton does not replace the version number in the cache. That's why if the Relaton code has been updated, it will always fetch all documents again without asking the cache. 
* In this case, Relaton should also "upgrade" the DB version when a newer Relaton version is run on an older cache.

The workaround is to remove `relaton/db/version` file, re-run, and the new version number will be written to the Relaton DB.

**Comment by andrew2net** [comment]
@ronaldtse we don't wipe local cache https://github.com/metanorma/relaton/issues/8#issuecomment-407985672
Do you thik we should do it now?

**Comment by opoudjis** [comment]
Btw, didn't I suggest somewhere using  a hash of the current Relaton grammar, instead of version numbers, to trigger flushing?

**Comment by ronaldtse** [comment]
@andrew2net in that comment, I mentioned:
> wiping clean the old-versioned cache, but we will need to ensure the local storage is not "wiped" (i.e. if the Relaton XML files are committed to git, we want the user to manually update them rather than delete them)?

i.e. We need to "upgrade" the cache DB.

> Btw, didn't I suggest somewhere using a hash of the current Relaton grammar, instead of version numbers, to trigger flushing?

This is the first time hearing this. And how would you suggest we do "hash of the current Relaton grammar"?

**Comment by andrew2net** [comment]
> i.e. We need to "upgrade" the cache DB.

@ronaldtse what do you mean "upgrade"?

**Comment by ronaldtse** [comment]
Make it functional for the new relaton version.

**Comment by andrew2net** [comment]
So we should delete a local cache the same way as we delete global one, do we? There isn't other functional concerned to relaton version changing.

**Comment by ronaldtse** [comment]
Right, there should not be functional differences between local and global cache. 

I am slightly concerned that the global relaton cache will be wiped by a newer relaton version though. However, I don’t think this can be fixed unless we have some data schema migration mechanism... thoughts?

**Comment by andrew2net** [comment]
Maybe we can create a new function `from_xml_X_X_X` each time we change the schema. So we can read XML files from a cache in an old format.
For example, if we put a version number into an XML file:
```
<bibitem>
  <version>0.5.2</version>
  ...
</bibitem>
```
then we can use function `from_xml_0_5_2` to parse the file.
With this approach, we don't have to clear cache at all.

**Comment by ronaldtse** [comment]
@andrew2net perhaps we can have something more generic, basically we need local data migration...

**Comment by andrew2net** [comment]
@ronaldtse when you say "data migration" do you mean we should convert XML files existed in a cache to new format instead of wiping the cache?

**Comment by opoudjis** [comment]
You've closed #43, but I think it's the only automatable way of tracking versions, and without it, things will be forgotten.

**Comment by ronaldtse** [comment]
@opoudjis please reopen that if desired. Thanks!

**Comment by andrew2net** [comment]
@opoudjis I'm trying to implement a tracking version of `relaton` by tracking changes in the `metanorma-model-iso`. To do it I add the `metanorma-model-iso` as a submodule to `relaton-bib` gem.
To be sure the submodule is updated and an XML file generated by `relaton-bib` is valid I try to validate the file:
```
schema = Nokogiri::XML::RelaxNG File.open "metanorma-model-iso/grammars/biblio.rng"
instance = Nokogiri::XML  File.open "spec/examples/bib_item.xml"
errors = schema.validate instance
expect(errors.empty?).to be_true
```
but got the error:
```
Failure/Error: schema = Nokogiri::XML::RelaxNG File.open "metanorma-model-iso/grammars/biblio.rng"

     Nokogiri::XML::SyntaxError:
       26:0: ERROR: Element <grammar> has no <start>
```
Could we make the grammar working in this case?

**Comment by opoudjis** [comment]
The source for the relaton grammar is not metanorma-model-iso: the relaton grammar is a submodule there, and is not updated online. The source is https://github.com/relaton/relaton-models/tree/master/grammars

> Could we make the grammar working in this case?

No. 

A Relax NG grammar can only contain one `start` tag, and the relaton grammar is included as part of the metanorma grammars. The only permissible start tag is of the grammar hosting the relaton grammar as an include—the root element of the metanorma document, in the case of metanorma.

If you were to use the grammar to do your own parsing of relaton or relaton collections, you would need to include the biblio.rng grammar inside another grammar, which does define a start tag. If you do need to validate the relaton schema (which I'm not convinced of), validate instead a shell schema invoking the relaton schema:

````
<grammar xmlns="http://relaxng.org/ns/structure/1.0" datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">
  <include href="biblio.rng"/>
  <start>
    <ref name="document"/>
  </start>
  <define name="document">
    <element name="document">
      <zeroOrMore>
        <ref name="bibitem"/>
      </zeroOrMore>
    </element>
  </define>
````

**Comment by andrew2net** [comment]
> If you do need to validate the relaton schema (which I'm not convinced of)

@opoudjis it isn't about schema validation. It's about to be sure no one forgets to update the submodule with grammar files. So when `to_xml` function is updated but the grammar isn't the test will fail.

**Comment by ronaldtse** [comment]
> A Relax NG grammar can only contain one start tag, and the relaton grammar is included as part of the metanorma grammars. The only permissible start tag is of the grammar hosting the relaton grammar as an include—the root element of the metanorma document, in the case of metanorma.

The Metanorma grammar should certainly be separate from the Relaton grammar. The include is what we should do in Metanorma.

>RELAX NG allows define elements to be put inside the include element to indicate that they are to replace definitions in the included grammar pattern. An include element can also contain a start element, which replaces the start in the included grammar pattern.

https://relaxng.org/tutorial-20030326.html

**Comment by opoudjis** [comment]
Notwithstanding, the start element for any relaton XML is not bibitem anyway, it's a relaton or relaton-collection root—which biblio.rnc does not currently define, because metanorma does not need it.

I should be able to override any start tag in biblio.rnc, I just find the requirement odd.

**Comment by opoudjis** [comment]
OK, @andrew2net, relaton now has `relaton-collection` as its start element, and that gets overwritten in basicdoc with `document`. Just make sure you're drawing from relaton/relaton-models.

**Comment by andrew2net** [comment]
@opoudjis thanks.
I just made an `rng` file with a start element and including `biblio.rng`. It shows me some invalidates in generated XML. I think it's a good idea to include grammar in each flavor gem to check generated XML. Will we have grammas for all relaton flavor gems in `relaton-models`?

**Comment by opoudjis** [comment]
> Will we have grammas for all relaton flavor gems in relaton-models?

No, only for those that publish their bibliographies online...
