### ISSUE TITLE
Separate the search cache (not-founds and redirects) and the data cache (only Relaton XML)

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton#56]
This issue requests separation of the search cache (not-founds and redirects) and the data cache (only Relaton XML).

The reason is to separate actual bibliographic handling (Relaton XML) with auto-fetching functionality (searching).

_Originally posted by @ronaldtse in https://github.com/relaton/relaton/issues/53#issuecomment-525434076_

**Comment by andrew2net** [comment]
@ronaldtse I suggest saving not-founds and redirects to files with `txt` extension (actually they are text, not XML files). So we can easy distinct them by extension.

**Comment by ronaldtse** [comment]
> @ronaldtse I suggest saving not-founds and redirects to files with `txt` extension (actually they are text, not XML files). So we can easy distinct them by extension.

That's... a little strange. Why don't we use `.notfound` and `.redirect` then?

**Comment by andrew2net** [comment]
@ronaldtse do you mean to put not-founds files into `.notfound` directory and redirects into `.redirect`?

**Comment by ronaldtse** [comment]
@andrew2net We could separate the directories to `not-found` and `redirect` as well for easy filtering.
