### ISSUE TITLE
Support un-fetchable data: gem-based overrides for data cache 

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton#57]
Sometimes not all bibdata can be retrieved from the endpoint, such as:

* ISO/IEC Directives (and also the "consolidated" copy) (from ISO) (https://github.com/relaton/relaton-iso/issues/35)
* ISO/IEC Directives (with IEC supplement) (from IEC)
* GB/T 1.1 (https://github.com/relaton/relaton-gb/issues/16)

We need to create data overrides for these. The format to be used is Relaton YAML, so someone can hand-craft the bibdata and push it to say, `relaton-iso`'s source.

This way the documents can be found via `relaton`.

**Comment by andrew2net** [comment]
@ronaldtse do you have any YAML file for testing the static database?

**Comment by ronaldtse** [comment]
@andrew2net these documents are great examples. Can you fill in the metadata for them?

**Comment by andrew2net** [comment]
@ronaldtse I'll try fo fill in some. How many such documents are there?

**Comment by ronaldtse** [comment]
@andrew2net see this for the IEC ones:
https://www.iec.ch/members_experts/refdocs/

<img width="1216" alt="Screen Shot 2019-09-18 at 3 39 31 PM" src="https://user-images.githubusercontent.com/11865/65127718-9aacac80-da2a-11e9-8f9e-1365a697d6eb.png">

**Comment by ronaldtse** [comment]
ISO:

* ISO/IEC Directives, Part 1. Consolidated ISO Supplement -- Procedures specific to ISO https://www.iso.org/sites/directives/current/consolidated/index.xhtml
* ISO/IEC Directives, Part 1. Procedures for the technical work. https://www.iso.org/sites/directives/current/part1/index.xhtml
* ISO/IEC Directives, Part 2. Principles and rules for the structure and drafting of ISO and IEC documents https://www.iso.org/sites/directives/current/part2/index.xhtml

**Comment by andrew2net** [comment]
> * ISO/IEC Directives, Part 1. Consolidated ISO Supplement -- Procedures specific to ISO
> * ISO/IEC Directives, Part 1. Procedures for the technical work
> * ISO/IEC Directives, Part 2. Principles and rules for the structure and drafting of ISO and IEC documents

Should users cite these documents by their full name? I.e. `ISO/IEC Directives, Part 1. Consolidated ISO Supplement -- Procedures specific to ISO`

**Comment by ronaldtse** [comment]
@andrew2net good question.

Are you asking about the "document identifier" used to cite the document for auto-fetch?

```adoc
[[[ISODP1,ISO/IEC Directives, Part 1]]], _title_
```
?

**Comment by ronaldtse** [comment]
In addition, there are also editions to think about. ISO Directives have changed according to year.

Maybe we have to define a syntax for them, e.g.:

```adoc
[[[ISODP1,ISO/IEC Directives Part 1 (2018)"
```

```adoc
[[[ISODP1,ISO/IEC Directives, Part 1 Consolidated ISO Supplement (2018)"
```

We generally lack a method of differentiating the same title of document against different publishers, e.g. ISO and IEC both publish the "ISO/IEC Directives, Part 1" but they are differently rendered. 

Ping @opoudjis

**Comment by andrew2net** [comment]
> * ISO/IEC Directives, Part 1. Consolidated ISO Supplement -- Procedures specific to ISO
> * ISO/IEC Directives, Part 1. Procedures for the technical work

These two documents have the same year but different editions

**Comment by ronaldtse** [comment]
@andrew2net these are actually two different documents. The content is different. This is why it’s confusing.

**Comment by andrew2net** [comment]
I've implemented this feature and push it as `feature/support-un-fetchable-data` branch. There is only one document in static database for now. We need to decide how to distinguish the references.

**Comment by ronaldtse** [comment]
> We need to decide how to distinguish the references.

Can you make a proposal?

**Comment by andrew2net** [comment]
We could distinguish these document by organisation and edition. For example:
- `ISO/IEC Directives Part 1 ISO-10` is "Consolidated ISO Supplement -- Procedures specific to ISO"
- `ISO/IEC Directives Part 1 ISO-15` is "Procedures for the technical work"
- `ISO/IEC Directives Part 2 ISO-8` is "Principles and rules for the structure and drafting of ISO and IEC documents"
- `ISO/IEC Directives Part 1 IEC-15` is "Procedures for the technical work - Procedures specific to IEC"

Following documents look identical:
- https://www.iso.org/sites/directives/current/consolidated/index.xhtml and https://www.iec.ch/members_experts/refdocs/iec/isoiecdir1%7Bed15.0%7Den.pdf
- https://www.iso.org/sites/directives/current/part2/index.xhtml and https://www.iec.ch/members_experts/refdocs/iec/isoiecdir2%7Bed8.0.RLV%7Den.pdf

**Comment by ronaldtse** [comment]
What does “ISO/10” mean? Published by ISO in 2010?

**Comment by ronaldtse** [comment]
@andrew2net oh `/10` the edition number? 

I think we need to differentiate them more than just the edition number.

For example, let's compare the cover pages of ISO's ISO/IEC Directives Part 1 -- base version vs Consolidated version.


BASE Version (Edition 15)

![](https://www.iso.org/sites/directives/current/part1/image/2.jpg)


CONSOLIDATED Version (Edition 10)

![](https://www.iso.org/sites/directives/current/consolidated/image/2.jpg)

I think the only thing we differentiate them is according to the title? Unless we assign a unique document identifier for them.

Look at how IEC refers to the IEC Consolidated version:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/11865/65291047-56352400-db84-11e9-8221-1b210bac3a7c.png">

The base versions alone:

<img width="903" alt="image" src="https://user-images.githubusercontent.com/11865/65291085-74028900-db84-11e9-97a1-bdfec26f8b34.png">

<img width="916" alt="Screen Shot 2019-09-20 at 8 56 36 AM" src="https://user-images.githubusercontent.com/11865/65291122-91375780-db84-11e9-863d-3fcfd16ab5b0.png">


The supplement alone:

<img width="902" alt="Screen Shot 2019-09-20 at 8 55 23 AM" src="https://user-images.githubusercontent.com/11865/65291062-64834000-db84-11e9-9856-eb96cd12cb38.png">


I think we can call them:

* `ISO/IEC DIR {n}` (base version)
* `ISO/IEC DIR {n} + {flavor} SUP` (consolidated version)
* `ISO/IEC DIR {flavor} SUP`.

And we have to document these in metanorma.com (and relation.com)

What do you think?

**Comment by ronaldtse** [comment]
There's also the strange JTC 1 supplement. we can do this for it:

* title: "ISO/IEC Directives, JTC 1 Supplement:2018"
* doc id: `ISO/IEC DIR JTC 1 SUP`

**Comment by andrew2net** [comment]
> `/10` the edition number?

Yes, it is.

I think the references should be simple as much as possible. Your suggestion looks consistent. So, let's do it?

**Comment by ronaldtse** [comment]
@andrew2net let's do it then!

**Comment by ronaldtse** [comment]
@andrew2net status? Thanks.

**Comment by andrew2net** [comment]
@ronaldtse here is an example https://github.com/relaton/relaton/blob/feature/support-un-fetchable-data/lib/relaton/static_cache/iso/iso_iec_directives_part_1.yml

**Comment by ronaldtse** [comment]
@andrew2net I had the need of citing `ISO/IEC DIR IEC SUPP` yesterday. Can you help document this functionality on `metanorma.com`?

**Comment by andrew2net** [comment]
@ronaldtse I didn't release it yet. Doing it now. Could you point where the documentation should be updated?
