### ISSUE TITLE
Sorting Relaton YAML in Jekyll

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton#58]
There is an issue with sorting Relaton YAML in Jekyll. Some of source files have `version.revision_date`, some doesn't. Some have `data` in a short format (only year) but `version.revision_date` in full.
So we need to use `version.revision_date` if it exists, if not use `date`. But it seems Jekyll doesn't have such a complex sorting.
In the old YAML we have a `revdate` field which seems is combination of `date` and `version.revision_date`.
In addition `date` and `version` are Jekyll's variables, it causes an error with `date.value` or `version.revision_date` as sort argument.
Maybe we should add a `revdate` to new Relaton YAML, and fill it with `revision_date` or `date` if `revision_date` doesn't exist.
Any thoughts?

**Comment by opoudjis** [comment]
I'm concerned about playing with a spec to address a tool's shortcomings. You can however add such a denormalised field to YAML, so long as it is never ever mapped back to Relaton XML, and is always generated from revision_date or date; it will need to be documented accordingly.

**Comment by andrew2net** [comment]
fixed it by https://github.com/relaton/relaton-bib/commit/e13a3e315569a255cd72fb51bd876b9a5d520a74
