### ISSUE TITLE
More informative error message for missing prefix

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton#63]
Andrej, the error message "does not have a recognised prefix" in relaton/lib/relaton/db.rb should point users to the documentation of prefixes in relaton/README.adoc. (Actually, it should point to relaton.com, but that's all it does.) Please add "See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them."

@ronaldtse if you want different text, let Andrej know.

**Comment by opoudjis** [comment]
Transferred from https://github.com/metanorma/metanorma-standoc/issues/143

**Comment by opoudjis** [comment]
This arose because Ronald forgot that all Chinese National Standards must be wrapped in "CN()" when calling Relaton, except when used within metanorma-gb.

**Comment by ronaldtse** [comment]
@opoudjis Again, that is untrue. GB, GB/T and GB/Z must be supported without any wrapper.

**Comment by ronaldtse** [comment]
Since @opoudjis has fixed the original issue, @andrew2net could you help act on this ticket so that the missing prefix message will be shown at the proper place? Thanks.
