### ISSUE TITLE
Add relaton-bsi

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton#86]
https://www.bsigroup.com/en-GB/

**Comment by ronaldtse** [comment]
We're going to scrape TechStreet's site for BSI content. The BSI shop has implement anti-crawl and is very slow.

**Comment by andrew2net** [comment]
@ronaldtse I've tried to crawl the https://shop.bsigroup.com/SearchResults and it works pretty well, has more details, has better page structure, and has more recent versions of the standards.

**Comment by ronaldtse** [comment]
OK then let's use that. However, aren't the pages slow?

**Comment by ronaldtse** [comment]
@andrew2net have you tried techstreet.com?

**Comment by andrew2net** [comment]
@ronaldtse yes, I have tried both and compared them.

**Comment by ronaldtse** [comment]
That’s great news — thanks!

**Comment by ronaldtse** [comment]
Repo access setup done.

**Comment by andrew2net** [comment]
@ronaldtse I can't find mandatory `doctype` for this [document](https://shop.bsigroup.com/ProductDetail?pid=000000000030382851).
Could we use one of these values as default?
```
DocumentType =
     "specification" |  "management-systems-standard" | "code-of-practice" |
           "guide" | "method-of-test" | "method-of-specifying" | "vocabulary" |
           "classification"
```

**Comment by ronaldtse** [comment]
This is an “adoption” document that was adopted from EN (CEN) which was adopted from ISO.

The BSI type should probably be a “specification”? Ping @opoudjis

**Comment by andrew2net** [comment]
@ronaldtse we don't have "adoption" in the list of allowed values.

**Comment by opoudjis** [comment]
It is a specification by default, yes.
