### ISSUE TITLE
Add relaton-cen

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton#87]
https://standards.cen.eu/dyn/www/f?p=CENWEB:105::RESET::::

**Comment by ronaldtse** [comment]
Repo created.

**Comment by andrew2net** [comment]
@opoudjis @ronaldtse I've tried to search the Cenelec documents on https://standards.cen.eu/dyn/www/f?p=CENWEB:105::RESET:::: using Ruby but it wasn't successful.
There is a site https://www.evs.ee/en/search where the documents can be fetched more easily. Do you mind if we fetch the documents from the site?

**Comment by ronaldtse** [comment]
EVS is a separate site, they offer Estonian standards. In any case we should link back to CENELECT. Which documents did you try?

**Comment by andrew2net** [comment]
@ronaldtse I've tried `CEN ISO/TS 13136`, `CWA 17025-111`, `EN 10048`

**Comment by ronaldtse** [comment]
I used this link: https://standards.cen.eu/dyn/www/f?p=CENWEB:105::RESET

Maybe the key point is to set the "Type" and "Standard Reference" accurately:

<img width="416" alt="Screenshot 2021-04-30 at 4 10 20 PM" src="https://user-images.githubusercontent.com/11865/116667259-91d5d800-a9ce-11eb-9ff9-140ec410ca07.png">

CEN ISO/TS 13136:

<img width="1017" alt="Screenshot 2021-04-30 at 4 08 24 PM" src="https://user-images.githubusercontent.com/11865/116667046-4cb1a600-a9ce-11eb-8ae3-72f14b9507a7.png">

CWA 17025-111:

<img width="1013" alt="Screenshot 2021-04-30 at 4 08 39 PM" src="https://user-images.githubusercontent.com/11865/116667072-55a27780-a9ce-11eb-8736-6912b3f5f6ec.png">

EN 10048:

<img width="1012" alt="Screenshot 2021-04-30 at 4 09 06 PM" src="https://user-images.githubusercontent.com/11865/116667128-65ba5700-a9ce-11eb-8cf3-c81be195c8d4.png">

**Comment by andrew2net** [comment]
> Maybe the key point is to set the "Type" and "Standard Reference" accurately:

@ronaldtse The search form on the site has hidden fields with ids but despite one of the fields is empty initially, it contains a value when the form is posting. I haven't found where the id's value comes from yet. Without the id, the server responds with an error. I've tried to use the id from the browser's request in the script and the server responds without error but it returns an empty search result. Maybe the value generated by javascript, it's necessary to do more investigation.
Also, the form has fields with the same names. It's allowed in HTML but Ruby doesn't allow Hash with identical keys. So it needs to make a function to generate POST request's body.
I've checked EVS and find out that the documents there are different, thus we can't use the site.

**Comment by andrew2net** [comment]
@ronaldtse @opoudjis how to map CEN's dates to BibliographicDateType's?
```
BibliographicDateType =
"published" | "accessed" | "created" | "implemented" | "obsoleted" | "confirmed" | "updated" | "issued" | "transmitted" | "copied" | "unchanged" | "circulated" | "adapted" | "vote-started" | "vote-ended"
```
date of Ratification (DOR) => ?
date of Availability (DAV) => ?
date of Announcement (DOA) => ?
date of Publication (DOP) => published
date of Withdrawal (DOW) => ?

**Comment by ronaldtse** [comment]
> date of Ratification (DOR) => ?

adapted

> date of Availability (DAV) => ?

issued

> date of Announcement (DOA) => ?

@opoudjis do we have one here? Or we add one.

> date of Withdrawal (DOW) => ?

obsoleted

**Comment by opoudjis** [comment]
Date of Announcement: we do have issued: Date a standard is authorised for publication. But you're already using that for Availability. So... no. And it is, I guess applicable even outside of standards: I was just trying to establish the date a book was written, based on the first time it was talked about in a speech.

So, yeah, we will need to add one, and I will update documentation accordingly, including relaton.org. It's extraneous to ISO 690, but what are you going to do. It will be of type "announced".

**Comment by andrew2net** [comment]
@opoudjis In workgroup grammar, there are attributes type and number.
The "CEN/CLC/JTC 21" mean type=JTC and number=21 however there are committees like "CEN/CLC/WS SEP2". In these cases, we can't store such a number because the grammar restricts the number attribute to be an integer.
Can we relax the restriction?

**Comment by opoudjis** [comment]
Yes, i'll do so tonight.

**Comment by andrew2net** [comment]
@opoudjis what type of relation should we use for the "Normative freference"?
![image](https://user-images.githubusercontent.com/5623890/119126171-fb2b9280-ba32-11eb-8b75-ff33523481b5.png)

**Comment by ronaldtse** [comment]
The “cite” relation should work for now. I’ve discussed with @opoudjis. Thanks!

**Comment by opoudjis** [comment]
Supersedes is "obsoletes"; Normative Reference is "cites".
