### ISSUE TITLE
Add relaton-cenelec

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton#88]
https://www.cenelec.eu/dyn/www/f?p=104:105:1340037120822001::::FSP_LANG_ID:25

**Comment by ronaldtse** [comment]
Repo created.

**Comment by andrew2net** [comment]
@ronaldtse @opoudjis does this issue duplicate https://github.com/relaton/relaton/issues/87 ?

**Comment by ronaldtse** [comment]
CEN and CENELEC are technically two separate organizations -- @andrew2net are you seeing some reason to only keep one of them?

**Comment by andrew2net** [comment]
> CEN and CENELEC are technically two separate organizations -- @andrew2net are you seeing some reason to only keep one of them?

@ronaldtse I've tried to look up some documents from CENELEC in CEN and vice versa. It seems CEN contains all the documents from CENELEC but not contrariwise.

**Comment by ronaldtse** [comment]
Then let’s just keep relaton-cen for now instead of needing relaton-cenelec. Thanks!
