### ISSUE TITLE
Add relaton-oasis

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton#89]

**Comment by andrew2net** [comment]
@ronaldtse should we fetch OASIS documents from (this)[https://www.oasis-open.org/standards/] site?

**Comment by ronaldtse** [comment]
Yes that is the correct one. Thanks!

**Comment by andrew2net** [comment]
@ronaldtse I assume that this is a group of documents. Part 0 has a reference [amqp-core-overview-v1.0], Part 1 has [amqp-core-types-v1.0], and so on. Am I right?

<img width="963" alt="image" src="https://user-images.githubusercontent.com/5623890/120555403-4e222400-c3fb-11eb-8e98-69c2f36cd733.png">

But some groups don't contain any parts or references. How could we cite them?

<img width="965" alt="image" src="https://user-images.githubusercontent.com/5623890/120556180-6fcfdb00-c3fc-11eb-8502-b466247604b2.png">

**Comment by ronaldtse** [comment]
> @ronaldtse I assume that this is a group of documents. Part 0 has a reference [amqp-core-overview-v1.0], Part 1 has [amqp-core-types-v1.0], and so on. Am I right?

Yes. The first screenshot displays the Part 0 standard and Part 1 standard of the "AMQP v1.0" standard series.

There are 2 cases here:
- user wants to refer to the whole series
- user wants to refer to a single part of the series

We need to support both.

In the case where a standard has no parts, we just cite them straight up using the name. This particular standard is accessible here: https://www.oasis-open.org/standard/bcm/ , but I don't see where the standards index page refers to it...

**Comment by andrew2net** [comment]
> * user wants to refer to the whole series

@ronaldtse do you have a suggestion on how to cite the whole series? I think using the `Advanced Message Queueing Protocol (AMQP) v1.0` as a reference is inconvenient. Maybe we can use the common part of the parts references in the series `amqp-core`.

> In the case where a standard has no parts, we just cite them straight up using the name. This particular standard is accessible here: https://www.oasis-open.org/standard/bcm/ , but I don't see where the standards index page refers to it...

The index page contains all the data that the separate page has, so we don't need to find the link you mentioned above.
The question is: how to cite such documents?

**Comment by ronaldtse** [comment]
> Maybe we can use the common part of the parts references in the series amqp-core

Agree, but this needs to be properly documented, especially this phrase is not available on the page but in the URL. 

Moreover, how do we deal with the versions? Is there another sample where there is a non 1.0 version number?

> The index page contains all the data that the separate page has, so we don't need to find the link you mentioned above.

The phrase “bcm” is not available except from this URL (standards/bcm).

**Comment by andrew2net** [comment]
> There are 2 cases here:
> 
> * user wants to refer to the whole series
> * user wants to refer to a single part of the series

@ronaldtse in case a standard has one part in a series do we need to have two documents to cite? For example "Advanced Message Queuing Protocol (AMQP) Enforcing Connection Uniqueness Version 1.0" [here](https://www.oasis-open.org/standards/):

<img width="865" alt="image" src="https://user-images.githubusercontent.com/5623890/155724414-15dd2a50-7e43-455c-9690-3321cecaad5c.png">

**Comment by ronaldtse** [comment]
> For example "Advanced Message Queuing Protocol (AMQP) Enforcing Connection Uniqueness Version 1.0"

This document seems to only be a single part document?

**Comment by andrew2net** [comment]
> This document seems to only be a single part document?

I think so.

**Comment by ronaldtse** [comment]
For some reason GitHub fails to move this issue to relaton-oasis. I have created https://github.com/relaton/relaton-oasis/issues/1 to supersede this one.
