### ISSUE TITLE
Relaton crash when behind corporate proxy / unable to connect to www.iso.org

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton#92]
User reports receiving this message:

```
$ metanorma --type iso foobar.adoc
 
/__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect': Failed to open TCP connection to www.iso.org:443 (getaddrinfo: nodename nor servname provided, or not known) (SocketError)
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
from /__enclose_io_memfs__/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
from /__enclose_io_memfs__/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:902:in `connect'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:876:in `start'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:608:in `start'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:485:in `get_response'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:462:in `get'
from /__enclose_io_memfs__/local/metanorma:179:in `<main>'
```

The error message says that it is unable to fetch from www.iso.org. This is because Metanorma is trying to retrieve bibliographic references defined in the file.

This failure is due to the user being behind a corporate proxy, and unable to connect to www.iso.org.

Relaton should not crash if it is unable to connect.

**Comment by andrew2net** [comment]
@ronaldtse I've checked all the HTTP requests in the relaton-iso. Each of them has a rescue from a SocketError. It isn't clear which line in relaton cause this error. Could you provide the full log?

**Comment by ronaldtse** [comment]
Asking user for a `metanorma -v` output.

**Comment by ronaldtse** [comment]
User replied with this. This rings a bell -- didn't we used to do a single check to ping www.iso.org see if the user is online!?

This user should be running the latest version, he installed via homebrew (`brew install metanorma/metanorma/metanorma`).

```
bash-3.2$ metanorma -v
/__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect': Failed to open TCP connection to www.iso.org:443 (getaddrinfo: nodename nor servname provided, or not known) (SocketError)
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
from /__enclose_io_memfs__/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
from /__enclose_io_memfs__/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:902:in `connect'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:876:in `start'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:608:in `start'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:485:in `get_response'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:462:in `get'
from /__enclose_io_memfs__/local/metanorma:179:in `<main>'
bash-3.2$ 
```

**Comment by andrew2net** [comment]
@ronaldtse It doesn't show the relaton is involved.
Looks like HTTP request is made in `local/metanorma:179`. What is `local/metanorma`? I'm able to find only `exe/metanorma` in the metanorma-cli but it is much shorter.

**Comment by ronaldtse** [comment]
It's actually this one...

https://github.com/metanorma/packed-mn/blob/5c8aefe418b8c0794e006db7b4f2933877962607/bin/metanorma#L177-L191

No wonder our binary is so slow!! Needs to get fixed ASAP...
