### ISSUE TITLE
primary attribute on docidentifier

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton#98]
Until now, an agreed rule between you and me, Andrej, is that I use the first docidentifier instance in a bibliographic record as the citation identifier for that record.

This... is informal. Moreover, it is entirely possible for a document to have two or three equally valid citation identifiers issued by different organisations, and to be used simultaneously in citation. 

For that reason, I request that you add `primary=true` to the docidentifier that is intended for citation use—and which has been, until now, the first docidentifier that appears. There may come a time when relaton generates records with multiple primary identifiers.

cc @strogonoff

**Comment by strogonoff** [comment]
@opoudjis, potentially there can be more than one `primary` document identifier, right?

**Comment by andrew2net** [comment]
@strogonoff it's not guaranteed only one `primary` document identifier but we can implement checking the restriction in the `Relaton::BibliographicItem` instance initialization.
I'm not sure if it is possible to describe the restriction in the LutaMl diagram or the grammar.

**Comment by ronaldtse** [comment]
@strogonoff we cannot only guarantee one `primary`. You can always interpret the "first primary" to be the real primary, and treat the others as non-primary. However this condition should be rare.

**Comment by strogonoff** [comment]
> @strogonoff we cannot only guarantee one `primary`. You can always interpret the "first primary" to be the real primary, and treat the others as non-primary. However this condition should be rare.

This would be fine except I can’t really depend on the order of docids in determining canonical link since it may change. If the property can appear on more than one docid, BibXML service won’t use it for canonical links at this time.

**Comment by andrew2net** [comment]
@ronaldtse for the `TRADE/WP.4/1068` reference the https://documents.un.org returns document with two symbols:
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/5623890/152994281-473f8d17-2cd8-478a-ae58-0142d6657e40.png">
The relaton-un parses the symbols as PubIDs. So we have two PubIDs for the document. Should we keep the first one only? Or keep both and mark first only as primary?

**Comment by ronaldtse** [comment]
@andrew2net good find. In this case there are two PubIDs and we should keep both. It seems that both of them are accepted, so it's hard to say...

**Comment by andrew2net** [comment]
@ronaldtse also the https://github.com/relaton/relaton-data-iso repo contains document `data/ISO_TC_184_SC_4_N1375.yaml` with two PubIDs.
